[project]
name = "mcp-prod-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "fastapi>=0.117.1",
    "fastmcp>=2.11.3",
]
